blank_issues_enabled: true
contact_links:
  - name: ArgilCAD Support
    url: https://argildesign.com/support.html
    about: For account, billing, and licensing questions please use our support page.
